### ISSUE TITLE
Is it possible to remove activerecord dependency

### ISSUE THREAD

**Issue by galetahub** [boltops-tools/jets#312]
Hi, thanks for your job,

Could we remove activerecord (and actionmailer) as the gem dependency?
For example, I'm using dynamoid and I don't need activerecord at all. 
In other words, developers can choose any other ORM, depending on their own cases

Thanks,
I can send a pull request if you agree with me :)

**Comment by tongueroo** [comment]
Sure. Think this makes sense. 

It probably a bit of work. The approach would take:

* add activerecord to the generated Gemfile instead of the jets.gemspec: https://github.com/tongueroo/jets/blob/master/lib/jets/commands/templates/skeleton/Gemfile.tt 
* Would also add activerecord the Jets Gemfile in the development and test group: https://github.com/tongueroo/jets/blob/master/Gemfile This is because some tests be testing with ActiveRecord. Am unsure. Noting in case. This is the trick I've used to include optional gems in the Jets test suite and probably the trickiest part.

**Comment by bitwerx-tyler** [comment]
Is there any progress on this? 

I have a project that won't use a DB at all and it would be nice to make Jets as lightweight as possible.

**Comment by pawptart** [comment]
Is there any progress on this?

I have a project that won't use a DB at all and it would be nice to make Jets as lightweight as possible.

**Comment by tongueroo** [comment]
Haven't see anything come yet. Happy to consider PRs for this. Otherwise, unsure when will take a look.

**Comment by pawptart** [comment]
Cool. I can take a look.

**Comment by pawptart** [comment]
This is looking like quite a bit of work. I expected it to be fairly integrated in Jets due to being built on Rails, but it's pretty extensive.

Unfortunately, it doesn't look like I'll have time to do this.

**Comment by tongueroo** [comment]
All good.

**Comment by timlawrenz** [comment]
@pawptart @tongueroo Do you want to keep this open?

**Comment by pawptart** [comment]
@timlawrenz I haven't looked at this since last September, I'm open to whatever.

**Comment by tongueroo** [comment]
Going to close out for now. Labeling it with backlog in a close state. Think may start using this approach to clean up issues and increase signal to noise.
