### ISSUE TITLE
Support for activerecord/activesupport 6.0

### ISSUE THREAD

**Issue by rinaldifonseca** [boltops-tools/jets#546]
## Summary

Hi! First of all, thanks for these great framework!
I would like suggest some alternative to support use Jets with activerecord/activesupport bellow 6.1.0. For exemple: 6.0.0

## Motivation

There is a lot of rubygems that normally depends from activesupport, activerecord and do not support the last versions from that gems. Eg:  I need to use the redshift-client gem, but it require to use activerecord 6.0.0 or bellow.

## Drawbacks

I understand that support really old versions will cost. But, at least, 2 latest versions maybe is a good investment in order to allow more people to use Jets.

**Comment by tongueroo** [comment]
Wondering which gem examples required 6.0 and below.

That being said, think it's ok to loosen the activesupport and the like to 6.0+ instead of 6.1+ in the jets.gemspec. Though, remembered there were some interfaces that changed from 6.0 to 6.1. Here's one example https://github.com/boltops-tools/jets/pull/539 There may be more.

So would need some `respond_to?` to check for what interface to use. Hence the overhead. Think it's worth investigating. Will review and consider PRs.

**Comment by rinaldifonseca** [comment]
Hi @tongueroo! Thanks  for the update!

Actually, there is no explicit dependency.
But in the **"activerecord6-redshift-adapter"** gem for example, the class active_record/connection_adapters/determine_if_preparable_visitor.rb is used in order to extend a module.
And that class do not exists in the ActiveRecord 6.1 version.

Is there some code to change in Jets in order to support 6.0+ ? If so, is there some path?

**Comment by rinaldifonseca** [comment]
Hi @tongueroo 

Is there some code to change in Jets in order to support 6.0+ ? If so, is there some path?

**Comment by mathieujobin** [comment]
@rinaldifonseca I am curious to hear out what exact issue you have with activesupport 6.0 ?

Have you tried using jets v2.3.19 ? The requirement to 6.1 was done with 3.0 jets release
or you could also fork jet and relax the requirement back to 6.0
