### ISSUE TITLE
webpacker for jets upgrade to 4.0.0

### ISSUE THREAD

**Issue by FernandoZX** [boltops-tools/jets#617]
I have a question about which webpacker gem is suggested for the framework because in my I have installed this on the gemfile:
`gem "webpacker", git: "https://github.com/tongueroo/webpacker.git", branch: "jets"`
that was forked by the user `https://github.com/tongueroo` exclusively for the framework jets
and in the yarn.lock I have installed the `@rails/webpacker` for with version 3.6.0.

By the way, i just want to upgrade the webpack rails from this version 3.6.0 to this version 4.0.0. but reading this guide https://github.com/rails/webpacker/blob/v4.0.0/docs/v4-upgrade.md i have to upgrade webpack gem and node package but this gem forked is only support for version 3.x.x webpacker described in features in this link https://github.com/tongueroo/webpacker/tree/jets 

Can you provide a suggestion for install webpack or upgrade above 3.x.x for any jets app?

thanks you.

addtional info:
gems:
* jets 3.0.23.
* webpacker (3.2.0).
node packages:
* @rails/webpacker@3.6.0

**Comment by tongueroo** [comment]
It seems that your jets app was built a while ago when the generator produced a Gemfile that uses the `tongueroo/webpacker` fork.

Suggest generating a new jets app and comparing. Just did that. 

Newly generated jets app use another gem called [jetpacker](https://github.com/tongueroo/jetpacker). It's still required a bit of hacking to get working but it's an improvement over the first approach. Jetpacker is currently based on the webpacker 5.2.1. See: https://github.com/tongueroo/jetpacker/blob/master/lib/webpacker/version.rb Also jetpacker has it's own version, current at 0.5.0 https://github.com/tongueroo/jetpacker/blob/master/lib/jetpacker/version.rb Took this approach more easily identify what version of webpack that Jets and the jetpacker gem is using.

Note: Have found with webpack generally, that updating the webpack related gems and yarn is usually not enough. Believe this is because the underlying node packages restructure their config file properties over time and then are not always backward compatible. Pretty much have to dig into each node package details to figure it out. 

It may be better to just generate a new app with latest babel.config.js, .browserslistrc, postcss.config.js, etc and compare. There may be more config files. This seems to be the nature of the best when it comes to webpacker. Closing out as prefer questions to be on the community forums. Thanks.

**Comment by FernandoZX** [comment]
> It seems that your jets app was built a while ago when the generator produced a Gemfile that uses the `tongueroo/webpacker` fork.
> 
> Suggest generating a new jets app and comparing. Just did that.
> 
> Newly generated jets app use another gem called [jetpacker](https://github.com/tongueroo/jetpacker). It's still required a bit of hacking to get working but it's an improvement over the first approach. Jetpacker is currently based on the webpacker 5.2.1. See: https://github.com/tongueroo/jetpacker/blob/master/lib/webpacker/version.rb Also jetpacker has it's own version, current at 0.5.0 https://github.com/tongueroo/jetpacker/blob/master/lib/jetpacker/version.rb Took this approach to more easily identify what version of webpack that Jets and the jetpacker gem is using.
> 
> Note: Have found with webpack generally, that updating the webpack related gems and yarn is usually not enough. Believe this is because the underlying node packages restructure their config file properties over time and then are not always backward compatible. Pretty much have to dig into each node package details to figure it out.
> 
> It may be better to just generate a new app with latest babel.config.js, .browserslistrc, postcss.config.js, etc and compare. There may be more config files. This seems to be the nature of the beast when it comes to webpacker. Closing out as prefer questions to be on the community forums. https://community.boltops.com/c/jets/5 Thanks.

ok @tongueroo , so the question is? Can I use jetpacker when I upgrade the node package `@rails/webpacker` from 3.6.0 to 4.0.0 or above in my app following in this guide provide by `@rails/webpacker` [upgrade rails/webpack from 3.x.x to 4.x.x ](https://github.com/rails/webpacker/blob/v4.0.0/docs/v4-upgrade.md) ?

kind regards

**Comment by tongueroo** [comment]
Unsure about 3.6 -> 4.0 specifically. In the newly generated jets app. Looks like `@rails/webpacker 5.2.1` and generally works. Debugging Session:

    $ jets -v
    3.1.1
    $ jets new demo
    $ cd demo
    $ head -3 node_modules/@rails/webpacker/package.json
    $ npm list | grep rails/webpacker
    ├─┬ @rails/webpacker@5.2.1
    $ 

Others might appreciate what you find out.
