### ISSUE TITLE
Files streaming

### ISSUE THREAD

**Issue by oleksiivykhor** [boltops-tools/jets#632]
Hello.
Is there a way to stream files using jets framework?
I was trying using https://github.com/WeTransfer/zip_tricks or ActionController::Live but it seems jets response does not support this.

**Comment by tongueroo** [comment]
Short answer: don’t think so. Locally you may be able to get it to work. But on AWS Lambda and API Gateway, it would work differently and wouldn’t work. So it’s a bit of work.

**Comment by oleksiivykhor** [comment]
@tongueroo sorry, but could you, please, explain a bit why that wouldn't work on AWS Lambda and API Gateway.
Docs say it's possible to work with binary files https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-content-encodings-examples-image-lambda.html

**Comment by tongueroo** [comment]
Oh I could be mistaken here. Was thinking about websocket streaming. For binary files like images, believe it works. But it’s been a while since tested. https://blog.boltops.com/2018/12/13/jets-image-upload-carrierwave-tutorial-binary-support/ Vaguely remember that had return a specific type of response for it to work. Jets should do this but your miles may vary. Binary data through APIGW seems to be a pain. You’d probably have a better experience using s3. So it may not work. At least wanted to provide an answer.

**Comment by oleksiivykhor** [comment]
@tongueroo thanks for your response (and the suggestion about the s3 approach, will check it out)

**Comment by carolkb4** [comment]
@oleksiivykhor How did you manage this? Going through the same...

**Comment by oleksiivykhor** [comment]
@carolkb4 so sorry, the only thing I can say, I've reached the goal using S3 (don't remember exactly how). It was more than 2 years ago, I don't work with that project anymore and can't revise the solution now.
